### ISSUE TITLE
SSO Issue

### ISSUE THREAD

**Issue by cloudwaves** [MicroHealthLLC/mSend#262]
Hi, I am unable to setup SSO ? is it working or still under development?

**Comment by bluenevus** [comment]
Sso works.  I'll update the install instructions.  Sorry when we forked we left the old install but today...it's far far from that baseline to get the additional features

On Jan 25, 2019 9:51 AM, cloudwaves <notifications@github.com> wrote:

Hi, I am unable to setup SSO ? is it working or still under development?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicroHealthLLC%2FmSend%2Fissues%2F262&data=02%7C01%7Cfrank.tucker%40microhealthllc.com%7Ca06331c7c009491104ce08d682d49f91%7C487ea2d67ea04a4b87736f4833ed2108%7C0%7C0%7C636840247072101955&sdata=QswTpILWqr5lKFCIcbykH3Ut44DCKIGoIlAwI6%2FyhMg%3D&reserved=0>, or mute the thread<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADgTo6433a-ZAjaseWEUFu9iOtUskhGUks5vGxn-gaJpZM4aTBSL&data=02%7C01%7Cfrank.tucker%40microhealthllc.com%7Ca06331c7c009491104ce08d682d49f91%7C487ea2d67ea04a4b87736f4833ed2108%7C0%7C0%7C636840247072111960&sdata=7r4bQVqbUXESkl0QBsSI5cZiRdRMBOejB0L5fF1aDsk%3D&reserved=0>.

SURVEY-Your anonymous feedback matters so tell me how I'm doing with 4 simple questions https://goo.gl/T7X7zU --- CONFIDENTIALITY NOTICE-If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited. Please notify the sender immediately by e-mail and delete this e-mail from your system. Thank You.

**Comment by cloudwaves** [comment]
Thanks for your immediate response... do you have any timeline to update the instructions?
Also whenever I navigate to the URL/saml_sso I see only blank page and I am not sure how to debug the issue...

________________________________

**Comment by bluenevus** [comment]
I'll update it today.  Monday at the latest.  Sso works. It's how we use it for ourselves

On Jan 25, 2019 10:08 AM, cloudwaves <notifications@github.com> wrote:
Thanks for your immediate response... do you have any timeline to update the instructions?
Also whenever I navigate to the URL/saml_sso I see only blank page and I am not sure how to debug the issue...

________________________________
