### ISSUE TITLE
Setup Error

### ISSUE THREAD

**Issue by cloudwaves** [MicroHealthLLC/mSend#263]
Hi,
Below is the new error when I try to setup from beginning.

There seems to be an error. Please try again.

PDOException: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'prev_assign' in /var/www/html/install/index.php:32 Stack trace: #0 /var/www/html/install/index.php(32): PDOStatement->execute(Array) #1 /var/www/html/install/index.php(109): try_query(Array) #2 {main}
PDOException: SQLSTATE[HY000]: General error: 1005 Can't create table `mmycloudsenddb`.`tbl_files_relations` (errno: 150 "Foreign key constraint is incorrectly formed") in /var/www/html/install/index.php:32 Stack trace: #0 /var/www/html/install/index.php(32): PDOStatement->execute(Array) #1 /var/www/html/install/index.php(109): try_query(Array) #2 {main}
PDOException: SQLSTATE[HY000]: General error: 1005 Can't create table `mmycloudsenddb`.`tbl_notifications` (errno: 150 "Foreign key constraint is incorrectly formed") in /var/www/html/install/index.php:32 Stack trace: #0 /var/www/html/install/index.php(32): PDOStatement->execute(Array) #1 /var/www/html/install/index.php(109): try_query(Array) #2 {main}
PDOException: SQLSTATE[HY000]: General error: 1005 Can't create table `mmycloudsenddb`.`tbl_downloads` (errno: 150 "Foreign key constraint is incorrectly formed") in /var/www/html/install/index.php:32 Stack trace: #0 /var/www/html/install/index.php(32): PDOStatement->execute(Array) #1 /var/www/html/install/index.php(109): try_query(Array) #2 {main}
PDOException: SQLSTATE[HY000]: General error: 1005 Can't create table `mmycloudsenddb`.`tbl_categories_relations` (errno: 150 "Foreign key constraint is incorrectly formed") in /var/www/html/install/index.php:32 Stack trace: #0 /var/www/html/install/index.php(32): PDOStatement->execute(Array) #1 /var/www/html/install/index.php(109): try_query(Array) #2 {main}

**Comment by bluenevus** [comment]
Yes...it's our terrible install instructions.  I'll fix it today... Me Monday at the latest

On Jan 25, 2019 11:14 AM, cloudwaves <notifications@github.com> wrote:

Hi,
Below is the new error when I try to setup from beginning.

There seems to be an error. Please try again.

PDOException: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'prev_assign' in /var/www/html/install/index.php:32 Stack trace: #0 /var/www/html/install/index.php(32): PDOStatement->execute(Array) #1<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicroHealthLLC%2FmSend%2Fissues%2F1&data=02%7C01%7Cfrank.tucker%40microhealthllc.com%7C781dd43fa7234f80c11f08d682e03410%7C487ea2d67ea04a4b87736f4833ed2108%7C0%7C0%7C636840296842358343&sdata=fCIU8bno1f1l%2FzE9YVX0%2FQ9BOszo8A5h3VLz%2Fstc7iM%3D&reserved=0> /var/www/html/install/index.php(109): try_query(Array) #2<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicroHealthLLC%2FmSend%2Fissues%2F2&data=02%7C01%7Cfrank.tucker%40microhealthllc.com%7C781dd43fa7234f80c11f08d682e03410%7C487ea2d67ea04a4b87736f4833ed2108%7C0%7C0%7C636840296842358343&sdata=lHKdIH342kufzPAESD1yCC4FxGrohFAZO9hGjW3B6P4%3D&reserved=0> {main}
PDOException: SQLSTATE[HY000]: General error: 1005 Can't create table mmycloudsenddb.tbl_files_relations (errno: 150 "Foreign key constraint is incorrectly formed") in /var/www/html/install/index.php:32 Stack trace: #0 /var/www/html/install/index.php(32): PDOStatement->execute(Array) #1<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicroHealthLLC%2FmSend%2Fissues%2F1&data=02%7C01%7Cfrank.tucker%40microhealthllc.com%7C781dd43fa7234f80c11f08d682e03410%7C487ea2d67ea04a4b87736f4833ed2108%7C0%7C0%7C636840296842514596&sdata=4F0%2Ff60AM0LPNa7TBg%2BduzNltP0%2BPbd01MNGdn8gQ7o%3D&reserved=0> /var/www/html/install/index.php(109): try_query(Array) #2<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicroHealthLLC%2FmSend%2Fissues%2F2&data=02%7C01%7Cfrank.tucker%40microhealthllc.com%7C781dd43fa7234f80c11f08d682e03410%7C487ea2d67ea04a4b87736f4833ed2108%7C0%7C0%7C636840296842514596&sdata=Xw0huw2wFRap5WOEImm%2Bw%2F82KprliXaHLz%2Bfnjmzrdo%3D&reserved=0> {main}
PDOException: SQLSTATE[HY000]: General error: 1005 Can't create table mmycloudsenddb.tbl_notifications (errno: 150 "Foreign key constraint is incorrectly formed") in /var/www/html/install/index.php:32 Stack trace: #0 /var/www/html/install/index.php(32): PDOStatement->execute(Array) #1<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicroHealthLLC%2FmSend%2Fissues%2F1&data=02%7C01%7Cfrank.tucker%40microhealthllc.com%7C781dd43fa7234f80c11f08d682e03410%7C487ea2d67ea04a4b87736f4833ed2108%7C0%7C0%7C636840296842514596&sdata=4F0%2Ff60AM0LPNa7TBg%2BduzNltP0%2BPbd01MNGdn8gQ7o%3D&reserved=0> /var/www/html/install/index.php(109): try_query(Array) #2<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicroHealthLLC%2FmSend%2Fissues%2F2&data=02%7C01%7Cfrank.tucker%40microhealthllc.com%7C781dd43fa7234f80c11f08d682e03410%7C487ea2d67ea04a4b87736f4833ed2108%7C0%7C0%7C636840296842514596&sdata=Xw0huw2wFRap5WOEImm%2Bw%2F82KprliXaHLz%2Bfnjmzrdo%3D&reserved=0> {main}
PDOException: SQLSTATE[HY000]: General error: 1005 Can't create table mmycloudsenddb.tbl_downloads (errno: 150 "Foreign key constraint is incorrectly formed") in /var/www/html/install/index.php:32 Stack trace: #0 /var/www/html/install/index.php(32): PDOStatement->execute(Array) #1<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicroHealthLLC%2FmSend%2Fissues%2F1&data=02%7C01%7Cfrank.tucker%40microhealthllc.com%7C781dd43fa7234f80c11f08d682e03410%7C487ea2d67ea04a4b87736f4833ed2108%7C0%7C0%7C636840296842514596&sdata=4F0%2Ff60AM0LPNa7TBg%2BduzNltP0%2BPbd01MNGdn8gQ7o%3D&reserved=0> /var/www/html/install/index.php(109): try_query(Array) #2<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicroHealthLLC%2FmSend%2Fissues%2F2&data=02%7C01%7Cfrank.tucker%40microhealthllc.com%7C781dd43fa7234f80c11f08d682e03410%7C487ea2d67ea04a4b87736f4833ed2108%7C0%7C0%7C636840296842514596&sdata=Xw0huw2wFRap5WOEImm%2Bw%2F82KprliXaHLz%2Bfnjmzrdo%3D&reserved=0> {main}
PDOException: SQLSTATE[HY000]: General error: 1005 Can't create table mmycloudsenddb.tbl_categories_relations (errno: 150 "Foreign key constraint is incorrectly formed") in /var/www/html/install/index.php:32 Stack trace: #0 /var/www/html/install/index.php(32): PDOStatement->execute(Array) #1<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicroHealthLLC%2FmSend%2Fissues%2F1&data=02%7C01%7Cfrank.tucker%40microhealthllc.com%7C781dd43fa7234f80c11f08d682e03410%7C487ea2d67ea04a4b87736f4833ed2108%7C0%7C0%7C636840296842514596&sdata=4F0%2Ff60AM0LPNa7TBg%2BduzNltP0%2BPbd01MNGdn8gQ7o%3D&reserved=0> /var/www/html/install/index.php(109): try_query(Array) #2<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicroHealthLLC%2FmSend%2Fissues%2F2&data=02%7C01%7Cfrank.tucker%40microhealthllc.com%7C781dd43fa7234f80c11f08d682e03410%7C487ea2d67ea04a4b87736f4833ed2108%7C0%7C0%7C636840296842514596&sdata=Xw0huw2wFRap5WOEImm%2Bw%2F82KprliXaHLz%2Bfnjmzrdo%3D&reserved=0> {main}

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicroHealthLLC%2FmSend%2Fissues%2F263&data=02%7C01%7Cfrank.tucker%40microhealthllc.com%7C781dd43fa7234f80c11f08d682e03410%7C487ea2d67ea04a4b87736f4833ed2108%7C0%7C0%7C636840296842514596&sdata=0Fj7ys%2BeoMqm6riO0%2BSRCX%2BhTCguIbNfic%2F4ufUBOaI%3D&reserved=0>, or mute the thread<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADgTo0ejGVPdZcHhF5PxJJKB3TvqRq29ks5vGy1sgaJpZM4aTLWs&data=02%7C01%7Cfrank.tucker%40microhealthllc.com%7C781dd43fa7234f80c11f08d682e03410%7C487ea2d67ea04a4b87736f4833ed2108%7C0%7C0%7C636840296842514596&sdata=003B83%2FFlXlgHcRJSRZJEvve8FpClkMH0A6ihtQwJRo%3D&reserved=0>.

SURVEY-Your anonymous feedback matters so tell me how I'm doing with 4 simple questions https://goo.gl/T7X7zU --- CONFIDENTIALITY NOTICE-If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited. Please notify the sender immediately by e-mail and delete this e-mail from your system. Thank You.
