### ISSUE TITLE
Having issues uploading large files by Upload Files; did not receive files not uploaded message

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSend#294]
Screenshot Example

![sent_files_upload_files_failed](https://user-images.githubusercontent.com/11938477/53042523-72d57600-3454-11e9-9de4-b7ee1eb4b876.jpg)

**Comment by cloudwaves** [comment]
yes, I do have the same issue...!

**Comment by cloudwaves** [comment]
why is this happening? unable to upload large files?

**Comment by bluenevus** [comment]
Need to set file size limit in php.ini to 2gb else it's like 2mb

On Mar 6, 2019 4:20 PM, cloudwaves <notifications@github.com> wrote:

why is this happening? unable to upload large files?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicroHealthLLC%2FmSend%2Fissues%2F294%23issuecomment-470281083&data=02%7C01%7Cfrank.tucker%40microhealthllc.com%7C18912dc4cc8d4fcb88ad08d6a2797918%7C487ea2d67ea04a4b87736f4833ed2108%7C0%7C1%7C636875040084828191&sdata=qIbDL3ebmd3lpyx2VYwcp0anMU5jcEme%2BoQkdERz0sk%3D&reserved=0>, or mute the thread<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADgTo7hoMMo59wHdP9J6W75oes8TDRyaks5vUDD3gaJpZM4bDuFn&data=02%7C01%7Cfrank.tucker%40microhealthllc.com%7C18912dc4cc8d4fcb88ad08d6a2797918%7C487ea2d67ea04a4b87736f4833ed2108%7C0%7C1%7C636875040084838196&sdata=VuPLkk3eIHpK5%2BQH5p9aXMyRTwcM0HfFPdb6dhBlxco%3D&reserved=0>.

--- CONFIDENTIALITY NOTICE-If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited. Please notify the sender immediately by e-mail and delete this e-mail from your system. Thank You.

**Comment by bluenevus** [comment]
just in case...here are your instructions


https://www.a2hosting.com/kb/developer-corner/php/using-php.ini-directives/php-maximum-upload-file-size


also, if you are behind a reverse proxy, you will have to configure the proxy for the upload size also

--
Dr. Frank Tucker
CEO
MicroHealth, LLC
People * Value * Innovation

O: (855) 294-3547 |  F: (855)-850-1264
Address:  8245 Boone Blvd, Suite 706  |  Vienna, VA 22182
<http://www.microhealthonline.com/>Email: frank.tucker@microhealthllc.com<mailto:frank.tucker@microhealthllc.com>
www.microhealthllc.com<http://www.microhealthllc.com/>

www.microhealthllc.com<http://www.microhealthllc.com/>

________________________________

**Comment by LAlexMHllc** [comment]
upload-process-form.php after uploading large file

![upload_process_form_after_upload_large_file](https://user-images.githubusercontent.com/11938477/59854840-a9a79400-9341-11e9-82ec-bb4ee07c7345.jpg)
