### ISSUE TITLE
When a user clicks the Go link in a DROP OFF REQUEST email and they are not logged in to mSend, after the user logs in using SAML, the browser should redirect to the dropoff screen for that corresponding request instead of https://send.microhealthllc.com/home.php

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSend#303]

**Comment by LAlexMHllc** [comment]
When user is already logged in using SAML or Sign In and clicks "Go" email link,  https://send.microhealthllc.com/dropoff.php?auth= displays as expected.

When user is NOT logged in and clicks "Go" email link, https://send.microhealthllc.com/?auth= displays as expected.
If user logs in using Sign In, then https://send.microhealthllc.com/dropoff.php?auth= displays as expected.
**BUT**, if user logs in using SAML, then https://send.microhealthllc.com/home.php displays instead of https://send.microhealthllc.com/dropoff.php?auth=. **THIS IS THE ISSUE**

**Comment by bluenevus** [comment]
doesn't matter whether saml or other authentication.  that is not the point.

The point is after authentication, it should go to the link that was originally clicked.  not home because they were told to upload and that is where the link took them.  the problem is the link assumes they are already logged in which manytimes they are not so they have to go to that step but be directed to the correct page from the originating link


--
Dr. Frank Tucker
CEO
MicroHealth, LLC
People * Value * Innovation

O: (855) 294-3547 |  F: (855)-850-1264
Address:  8245 Boone Blvd, Suite 706  |  Vienna, VA 22182
<http://www.microhealthonline.com/>Email: frank.tucker@microhealthllc.com<mailto:frank.tucker@microhealthllc.com>
www.microhealthllc.com<http://www.microhealthllc.com/>

www.microhealthllc.com<http://www.microhealthllc.com/>

________________________________
